
version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./config:/etc/mongo/
    command: [ 
      '--auth',
      '--config',
      '/etc/mongo/mongod.conf'
    ]
volumes:
  dbdata6: